version: '3.5'
services:
  php_cli:
    image: qazaq_genius/lyrics_api/php_cli:dev
    container_name: qazaq_genius_lyrics_api_php_cli
    working_dir: /var/www/html
    volumes:
      - ./../../code:/var/www/html
    environment:
      - VHOST=localhost