# /.github/workflows/uberspace-deploy.yml
# Warning: deletes all files on uberspace which are not in repo, use without --delete if unsure
name: Deploy
on:
  push:
    branches:
      - 14-uberspace-deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        args: --profile --ignore-platform-reqs --working-dir=code
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: /
        remote_path: /home/${{ secrets.UBERSPACE_USER }}/html/staging.r0.fyi
        remote_host: ${{ secrets.UBERSPACE_HOST }}
        remote_user: ${{ secrets.UBERSPACE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}